// SIGNUP
export const SIGNUP_INIT = "SIGNUP_INIT";
export const SIGNUP_RESET = "SIGNUP_RESET";
export const SIGNUP_COMPLETED = "SIGNUP_COMPLETED";
export const SIGNUP_FAILED = "SIGNUP_FAILED";

// VALIDATE
export const VALIDATE_INIT = "VALIDATE_INIT";
export const VALIDATE_COMPLETED = "VALIDATE_COMPLETED";
export const VALIDATE_FAILED = "VALIDATE_FAILED";

// LOGIN
export const LOGIN_INIT = "LOGIN_INIT";
export const LOGIN_COMPLETED = "LOGIN_COMPLETED";
export const LOGIN_FAILED = "LOGIN_FAILED";

// AUTH
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGOUT = "LOGOUT";
